library(readxl)
FeaturesPremiumCRating2 <- read_excel("FeaturesPremiumCRating2.xlsx")
View(FeaturesPremiumCRating2)
library(readxl)
FeaturesPremiumCRating <- read_excel("FeaturesPremiumCRating.xlsx")
View(FeaturesPremiumCRating)
library(ggbiplot)
#FPcost.pca <- prcomp(FeaturesPremiumCRating[,c(1:15)],center=TRUE,scale.=TRUE)
FPfeat.pca <- prcomp(FeaturesPremiumCRating[,c(18:38)],center=TRUE,scale.=TRUE)
View(FPfeat.pca)
View(FeaturesPremiumCRating2)
View(FPfeat.pca)
library(readxl)
FeaturesPremiumCRating <- read_excel("FeaturesPremiumCRating.xlsx")
View(FeaturesPremiumCRating)
FP.gender <- c(rep("Female",2),"Male","Female",rep("Male",6),"Female","Male","Female",rep("Male",2),"Female","Male",rep("Female",2),rep("Male",2))
FP.type <- c("Rechargeable",rep("Manual",6),"Rechargeable Manual",rep("Manual",5),"Rechargeable",rep("Manual",5),"Rechargeable","Manual")
costcluster <- kmeans(FeaturesPremiumCRating[,c(1:15)],3,trace = TRUE)
#pairs(FeaturesPremiumCRating[,c(18:38)],labels = c("Grip","Weight","On/Off","Clean/Rinse","Vibration","Waterproof","Travel","Replaceable Battery","Replaceable Brush Head","Replacement Cost","Availability","Long Batt Life","Technology","Looks cool","Distinguishable","Match decor","Easy to store","Small space","Easy to hold","Toothbrush sized","Packaging"),main="Characteristics Ratings")
summary(FPfeat.pca)
print(FPfeat.pca)
library(ggbiplot)
libray(devtools)
library(devtools)
install_github("vqv/ggbiplot")
library(devtools)
library(tools)
install_github("vqv/ggbiplot")
library(tools)
install("vqv/ggbiplot")
install.packages(ggbiplot)
install.packages("ggbiplot")
install.packages("ggplot2")
#FPcost.pca <- prcomp(FeaturesPremiumCRating[,c(1:15)],center=TRUE,scale.=TRUE)
FPfeat.pca <- prcomp(FeaturesPremiumCRating[,c(18:38)],center=TRUE,scale.=TRUE)
print(FPfeat.pca)
ggbiplot(FPfeat.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE, groups=FP.type)+ggtitle("FP feature with type")
ggplot2(FPfeat.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE, groups=FP.type)+ggtitle("FP feature with type")
library(ggplot2)
print(FPfeat.pca)
FPcost.pca <- prcomp(FeaturesPremiumCRating[,c(1:15)],center=TRUE,scale.=TRUE)
FPfeat.pca <- prcomp(FeaturesPremiumCRating[,c(18:38)],center=TRUE,scale.=TRUE)
FP.gender <- c(rep("Female",2),"Male","Female",rep("Male",6),"Female","Male","Female",rep("Male",2),"Female","Male",rep("Female",2),rep("Male",2))
FP.type <- c("Rechargeable",rep("Manual",6),"Rechargeable Manual",rep("Manual",5),"Rechargeable",rep("Manual",5),"Rechargeable","Manual")
library(ggplot2)
print(FPfeat.pca)
costcluster <- kmeans(FeaturesPremiumCRating[,c(1:15)],3,trace = TRUE)
plot(FeaturesPremiumCRating[,c(1:2)],col=costcluster)
plot(FeaturesPremiumCRating[,c(1:2)],col=costcluster)
ggplot2(FPcost.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE,groups=FP.gender)+ggtitle("FP cost with gender")
library(devtools)
install_github("vqv/ggbiplot")
autoplot(pca_res)
(ggfortify)
library(tools)
library(tools)
library(tools)
install.packages("ggplot2")
install.packages("ggplot2")
install.packages("ggplot2")
library(ggfortify)
library(tools)
install.packages("ggplot2")
library(devtools)
install_github("vqv/ggbiplot")
install_github("vqv/ggbiplot")
#import excel before this
FeaturesPremiumCRating
#categorising
fp<-(FeaturesPremiumCRating[, 1:15])
gender <- (FeaturesPremiumCRating[, 16])
type <- (FeaturesPremiumCRating[, 17])
crating<-(FeaturesPremiumCRating[, 18:38])
#double checking categories
fp
gender
type
crating
#pca of features premium
fp.pca <- prcomp(FeaturesPremiumCRating[, 1:15], center=TRUE, scale = TRUE)
print(fp.pca)
plot(fp.pca, type ="l")
summary(fp.pca)
library(devtools)
install_github("vqv/ggbiplot")
install.packages(devtools)
install.packages("devtools")
library(devtools)
dir
library(devtools)
install_github("vqv/ggbiplot")
FPcost.pca <- prcomp(FeaturesPremiumCRating[,c(1:15)],center=TRUE,scale.=TRUE)
FPfeat.pca <- prcomp(FeaturesPremiumCRating[,c(18:38)],center=TRUE,scale.=TRUE)
FP.gender <- c(rep("Female",2),"Male","Female",rep("Male",6),"Female","Male","Female",rep("Male",2),"Female","Male",rep("Female",2),rep("Male",2))
FP.type <- c("Rechargeable",rep("Manual",6),"Rechargeable Manual",rep("Manual",5),"Rechargeable",rep("Manual",5),"Rechargeable","Manual")
library(ggplot2)
print(FPfeat.pca)
costcluster <- kmeans(FeaturesPremiumCRating[,c(1:15)],3,trace = TRUE)
plot(FeaturesPremiumCRating[,c(1:2)],col=costcluster)
ggplot2(FPcost.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE,groups=FP.gender)+ggtitle("FP cost with gender")
ggplot2(FPcost.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE,groups=FP.type)+ggtitle("FP cost with type")
ggplot2(FPfeat.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE,groups=FP.gender)+ggtitle("FP feature with gender")
ggplot2(FPfeat.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE, groups=FP.type)+ggtitle("FP feature with type")
#pairs(FeaturesPremiumCRating[,c(1:15)],labels=c("Timer","Pacer","Rechargeable","Distinguishable","Style","Stand","Head storage","Travel storage","Dual speed","Charity","Warranty","Built-in toothpaste","Battery indicator","Attachments","Extra head"),main="How much they are willing to pay for what function")
#pairs(FeaturesPremiumCRating[,c(18:38)],labels = c("Grip","Weight","On/Off","Clean/Rinse","Vibration","Waterproof","Travel","Replaceable Battery","Replaceable Brush Head","Replacement Cost","Availability","Long Batt Life","Technology","Looks cool","Distinguishable","Match decor","Easy to store","Small space","Easy to hold","Toothbrush sized","Packaging"),main="Characteristics Ratings")
#summary(FPfeat.pca)
FPcost.pca <- prcomp(FeaturesPremiumCRating[,c(1:15)],center=TRUE,scale.=TRUE)
FPfeat.pca <- prcomp(FeaturesPremiumCRating[,c(18:38)],center=TRUE,scale.=TRUE)
FP.gender <- c(rep("Female",2),"Male","Female",rep("Male",6),"Female","Male","Female",rep("Male",2),"Female","Male",rep("Female",2),rep("Male",2))
FP.type <- c("Rechargeable",rep("Manual",6),"Rechargeable Manual",rep("Manual",5),"Rechargeable",rep("Manual",5),"Rechargeable","Manual")
library(ggbiplot)
print(FPfeat.pca)
costcluster <- kmeans(FeaturesPremiumCRating[,c(1:15)],3,trace = TRUE)
plot(FeaturesPremiumCRating[,c(1:2)],col=costcluster)
ggbiplot(FPcost.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE,groups=FP.gender)+ggtitle("FP cost with gender")
ggbiplot(FPcost.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE,groups=FP.type)+ggtitle("FP cost with type")
ggbiplot(FPfeat.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE,groups=FP.gender)+ggtitle("FP feature with gender")
ggbiplot(FPfeat.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE, groups=FP.type)+ggtitle("FP feature with type")
#pairs(FeaturesPremiumCRating[,c(1:15)],labels=c("Timer","Pacer","Rechargeable","Distinguishable","Style","Stand","Head storage","Travel storage","Dual speed","Charity","Warranty","Built-in toothpaste","Battery indicator","Attachments","Extra head"),main="How much they are willing to pay for what function")
#pairs(FeaturesPremiumCRating[,c(18:38)],labels = c("Grip","Weight","On/Off","Clean/Rinse","Vibration","Waterproof","Travel","Replaceable Battery","Replaceable Brush Head","Replacement Cost","Availability","Long Batt Life","Technology","Looks cool","Distinguishable","Match decor","Easy to store","Small space","Easy to hold","Toothbrush sized","Packaging"),main="Characteristics Ratings")
#summary(FPfeat.pca)
FPfeat.pca <- prcomp(FeaturesPremiumCRating[,c(18:38)],center=TRUE,scale.=TRUE)
ggbiplot(FPfeat.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE,groups=FP.gender)+ggtitle("FP feature with gender")
#
summary(FPfeat.pca)
#pairs(FeaturesPremiumCRating[,c(18:38)],labels = c("Grip","Weight","On/Off","Clean/Rinse","Vibration","Waterproof","Travel","Replaceable Battery","Replaceable Brush Head","Replacement Cost","Availability","Long Batt Life","Technology","Looks cool","Distinguishable","Match decor","Easy to store","Small space","Easy to hold","Toothbrush sized","Packaging"),main="Characteristics Ratings")
summary(FPfeat.pca)
pairs(FeaturesPremiumCRating[,c(1:15)],labels=c("Timer","Pacer","Rechargeable","Distinguishable","Style","Stand","Head storage","Travel storage","Dual speed","Charity","Warranty","Built-in toothpaste","Battery indicator","Attachments","Extra head"),main="How much they are willing to pay for what function")
#pairs(FeaturesPremiumCRating[,c(18:38)],labels = c("Grip","Weight","On/Off","Clean/Rinse","Vibration","Waterproof","Travel","Replaceable Battery","Replaceable Brush Head","Replacement Cost","Availability","Long Batt Life","Technology","Looks cool","Distinguishable","Match decor","Easy to store","Small space","Easy to hold","Toothbrush sized","Packaging"),main="Characteristics Ratings")
summary(FPfeat.pca)
ggbiplot(FPcost.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE,groups=FP.gender)+ggtitle("FP cost with gender")
library(readxl)
FeaturesPremiumCRating2 <- read_excel("FeaturesPremiumCRating2.xlsx",
col_names = FALSE)
View(FeaturesPremiumCRating2)
ggbiplot(FPcost.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating2),var.axes = FALSE,groups=FP.gender)+ggtitle("FP cost with gender")
#pairs(FeaturesPremiumCRating2[,c(18:38)],labels = c("Grip","Weight","On/Off","Clean/Rinse","Vibration","Waterproof","Travel","Replaceable Battery","Replaceable Brush Head","Replacement Cost","Availability","Long Batt Life","Technology","Looks cool","Distinguishable","Match decor","Easy to store","Small space","Easy to hold","Toothbrush sized","Packaging"),main="Characteristics Ratings")
summary(FPfeat.pca)
ggbiplot(FPfeat.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating2),var.axes = FALSE, groups=FP.type)+ggtitle("FP feature with type")
FPcost.pca <- prcomp(FeaturesPremiumCRating[,c(1:15)],center=TRUE,scale.=TRUE)
FPfeat.pca <- prcomp(FeaturesPremiumCRating[,c(18:38)],center=TRUE,scale.=TRUE)
FP.gender <- c(rep("Female",2),"Male","Female",rep("Male",6),"Female","Male","Female",rep("Male",2),"Female","Male",rep("Female",2),rep("Male",2))
FP.type <- c("Rechargeable",rep("Manual",6),"Rechargeable Manual",rep("Manual",5),"Rechargeable",rep("Manual",5),"Rechargeable","Manual")
library(ggbiplot)
print(FPfeat.pca)
costcluster <- kmeans(FeaturesPremiumCRating[,c(1:15)],3,trace = TRUE)
plot(FeaturesPremiumCRating[,c(1:2)],col=costcluster)
ggbiplot(FPcost.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE,groups=FP.gender)+ggtitle("FP cost with gender")
ggbiplot(FPcost.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE,groups=FP.type)+ggtitle("FP cost with type")
ggbiplot(FPfeat.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE,groups=FP.gender)+ggtitle("FP feature with gender")
ggbiplot(FPfeat.pca,ellipse=TRUE,labels=rownames(FeaturesPremiumCRating),var.axes = FALSE, groups=FP.type)+ggtitle("FP feature with type")
#pairs(FeaturesPremiumCRating[,c(1:15)],labels=c("Timer","Pacer","Rechargeable","Distinguishable","Style","Stand","Head storage","Travel storage","Dual speed","Charity","Warranty","Built-in toothpaste","Battery indicator","Attachments","Extra head"),main="How much they are willing to pay for what function")
#pairs(FeaturesPremiumCRating[,c(18:38)],labels = c("Grip","Weight","On/Off","Clean/Rinse","Vibration","Waterproof","Travel","Replaceable Battery","Replaceable Brush Head","Replacement Cost","Availability","Long Batt Life","Technology","Looks cool","Distinguishable","Match decor","Easy to store","Small space","Easy to hold","Toothbrush sized","Packaging"),main="Characteristics Ratings")
summary(FPfeat.pca)
FP.gender <- c(rep("Female",2),"Male","Female",rep("Male",6),"Female","Male","Female",rep("Male",2),"Female","Male",rep("Female",2),rep("Male",2))
